### ISSUE TITLE
User defined accelerator architecture not working

### ISSUE THREAD

**Issue by rderi** [ZigZag-Project/zigzag#48]
Hi,

I've been experimenting with ZigZag for a class project and I wanted to see if I could generate memory hierarchies using a genetic algorithm, then evaluate its performance with ZigZag. To test my class that converts genomes to ZigZag architecture descriptions, I tried to recreate TPU_like and run `get_hardware_performance_zigzag()` on it. However, I get the following error:
```
Traceback (most recent call last):
  File "/Users/rderi/Programming/.venv/lib/python3.12/site-packages/zigzag/classes/stages/SpatialMappingConversionStage.py", line 55, in run
    spatial_mapping, spatial_mapping_int = self.convert_user_spatial_mapping(
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rderi/Programming/.venv/lib/python3.12/site-packages/zigzag/classes/stages/SpatialMappingConversionStage.py", line 144, in convert_user_spatial_mapping
    self.generate_limited_user_spatial_mapping(
  File "/Users/rderi/Programming/.venv/lib/python3.12/site-packages/zigzag/classes/stages/SpatialMappingConversionStage.py", line 227, in generate_limited_user_spatial_mapping
    oa_dim_size = next(
                  ^^^^^
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/Users/rderi/.vscode/extensions/ms-python.debugpy-2024.0.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/rderi/.vscode/extensions/ms-python.debugpy-2024.0.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/rderi/.vscode/extensions/ms-python.debugpy-2024.0.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/rderi/.vscode/extensions/ms-python.debugpy-2024.0.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rderi/.vscode/extensions/ms-python.debugpy-2024.0.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/rderi/.vscode/extensions/ms-python.debugpy-2024.0.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/rderi/Programming/Class/COSC461-S24/final/test/hierarchy_test.py", line 208, in <module>
    main()
  File "/Users/rderi/Programming/Class/COSC461-S24/final/test/hierarchy_test.py", line 195, in main
    energy, latency, cme = get_hardware_performance_zigzag(workload=workload,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rderi/Programming/.venv/lib/python3.12/site-packages/zigzag/api.py", line 78, in get_hardware_performance_zigzag
    answers = mainstage.run()
              ^^^^^^^^^^^^^^^
  File "/Users/rderi/Programming/.venv/lib/python3.12/site-packages/zigzag/classes/stages/Stage.py", line 49, in run
    for cme, extra_info in self.list_of_callables[0](
  File "/Users/rderi/Programming/.venv/lib/python3.12/site-packages/zigzag/classes/stages/ONNXModelParserStage.py", line 28, in run
    for cme, extra_info in sub_stage.run():
  File "/Users/rderi/Programming/.venv/lib/python3.12/site-packages/zigzag/classes/stages/MainInputParserStages.py", line 21, in run
    for cme, extra_info in sub_stage.run():
  File "/Users/rderi/Programming/.venv/lib/python3.12/site-packages/zigzag/classes/stages/SaveStage.py", line 99, in run
    for id, (cme, extra_info) in enumerate(substage.run()):
  File "/Users/rderi/Programming/.venv/lib/python3.12/site-packages/zigzag/classes/stages/SaveStage.py", line 148, in run
    for id, (cme, extra_info) in enumerate(substage.run()):
  File "/Users/rderi/Programming/.venv/lib/python3.12/site-packages/zigzag/classes/stages/ReduceStages.py", line 122, in run
    for cme, extra_info in substage.run():
  File "/Users/rderi/Programming/.venv/lib/python3.12/site-packages/zigzag/classes/stages/WorkloadStage.py", line 47, in run
    for cme, extra_info in sub_stage.run():
  File "/Users/rderi/Programming/.venv/lib/python3.12/site-packages/zigzag/classes/stages/SaveStage.py", line 34, in run
    for id, (cme, extra_info) in enumerate(substage.run()):
  File "/Users/rderi/Programming/.venv/lib/python3.12/site-packages/zigzag/classes/stages/ReduceStages.py", line 30, in run
    for cme, extra_info in substage.run():
  File "/Users/rderi/Programming/.venv/lib/python3.12/site-packages/zigzag/classes/stages/SpatialMappingGeneratorStage.py", line 156, in run
    for cme, extra_info in spatial_mapping_conversion_stage.run():
RuntimeError: generator raised StopIteration
```

This makes me wonder, does ZigZag support user-defined architectures as well? And if yes, what might've went wrong here? I know this might be a lot to read, but I'd appreciate any help.

My code, for reference

_hierarchy.py_
```
import numpy as np
from zigzag.classes.hardware.architecture.memory_instance import MemoryInstance
from zigzag.classes.hardware.architecture.memory_hierarchy import MemoryHierarchy
from zigzag.classes.hardware.architecture.core import Core
from zigzag.classes.hardware.architecture.accelerator import Accelerator



class Hierarchy:
    gene_dtype = np.int8
    def __init__(self, memory_instances, operational_array, genome):
        self.memory_instances = memory_instances
        self.n_memory_instances = len(memory_instances)
        self.operational_array = operational_array
        self.n_dims = len(operational_array.dimensions)
        self.genome = genome
        self._build_hierarchy_from_genome(genome)
    
    
    def _calculate_memory_instance_genome_length(self):
        return (
            1                   # memory_instance
            + 3                 # operands
            + 3 * 8             # port_alloc
            + self.n_dims       # served_dimensions
        )
    
    def _split_genome_into_memory_nodes(self, genome):
        memory_instance_length = self._calculate_memory_instance_genome_length()
        memory_nodes = np.zeros((self.n_memory_instances, memory_instance_length), dtype=self.gene_dtype)
        
        if len(genome) % memory_instance_length != 0:
            raise ValueError("Invalid genome length.")
        
        for i in range(self.n_memory_instances):
            memory_nodes[i] = np.array(genome[i * memory_instance_length : (i + 1) * memory_instance_length], dtype=self.gene_dtype)
        
        return memory_nodes
    
    def _generate_dimension_tuple(self, dim = None):
        tup = np.zeros(self.n_dims, dtype=self.gene_dtype)
        if dim is not None:
            tup[dim] = 1
        return tuple(tup)
        
        
    def _build_hierarchy_from_genome(self, genome):
        self.memory_hierarchy_graph = MemoryHierarchy(operational_array=self.operational_array) 
        memory_nodes = self._split_genome_into_memory_nodes(genome)
        
        for memory_node in memory_nodes:
            
            #Step 1. Select memory instance based on idx stored in first gene
            memory_instance = self.memory_instances[int(memory_node[0])]
            
            #Step 2. Set memory operands based on the next 3 genes
            operands = ()
            
            #Values are 1 or 0 / truish or falsish
            I1_operand = memory_node[1]
            I2_operand = memory_node[2]
            O_operand = memory_node[3]
            
            if I1_operand:
                operands += ("I1",)
            if I2_operand:
                operands += ("I2",)
            if O_operand:
                operands += ("O",)
            
            #TODO: break if no operands are being used
                
            #Step 3. Set port_alloc based on the next 24 genes
            port_alloc = ()
            
            
            port_genes = []
            if I1_operand:
                port_genes += [memory_node[4:12]]
            if I2_operand:
                port_genes += [memory_node[12:20]]
            if O_operand:
                port_genes += [memory_node[20:28]]
            
            for port_gene in port_genes:
                operand_port_alloc = {}
                ports = ['fh', 'fl', 'th', 'tl']
                for i in range(len(ports)):
                    curr_port = ports[i]
                    
                    curr_port_idx = i * 2 #Every port is represented by two genes
                    port_type = None if port_gene[curr_port_idx] == 0 \
                                else "r" if port_gene[curr_port_idx] == 1 \
                                else 'w' if port_gene[curr_port_idx] == 2 \
                                else "rw"
                    port_number = port_gene[curr_port_idx + 1]
                    
                    port_str = f"{port_type}_port_{port_number}" if port_type is not None else None
                    
                    operand_port_alloc[curr_port] = port_str
                port_alloc += (operand_port_alloc,)
            
            #Step 4. Set served_dimensions based on the next n_dims genes
            dimension_genes = memory_node[28 : 28 + self.n_dims]
            served_dimensions = set()
            n_served_dims = np.sum(dimension_genes)
            if n_served_dims == self.n_dims:
                served_dimensions = "all"
            elif n_served_dims == 0:
                served_dimensions.add(self._generate_dimension_tuple(None))
            
            else:
                for i in range(self.n_dims):
                    if dimension_genes[i] == 1:
                        served_dimensions.add(self._generate_dimension_tuple(i))
            
            #We're done, so we can add everything to the memory hierarchy graph
            self.memory_hierarchy_graph.add_memory(
                memory_instance=memory_instance,
                operands=operands,
                port_alloc=port_alloc,
                served_dimensions=served_dimensions
            )
    def get_core(self):
        core1 = Core(1, self.operational_array, self.memory_hierarchy_graph)
        return {core1}
        
    def get_accelerator(self):
        cores = self.get_core()
        return Accelerator('acc', self.get_core())        
```

_hierarchy_test.py_
```
from zigzag.classes.hardware.architecture.memory_hierarchy import MemoryHierarchy
from zigzag.classes.hardware.architecture.memory_level import MemoryLevel
from zigzag.classes.hardware.architecture.operational_unit import Multiplier
from zigzag.classes.hardware.architecture.operational_array import MultiplierArray
from zigzag.classes.hardware.architecture.memory_instance import MemoryInstance
from zigzag.classes.hardware.architecture.accelerator import Accelerator
from zigzag.classes.hardware.architecture.core import Core
from zigzag.api import get_hardware_performance_zigzag

import numpy as np

#Import hierarchy.py from parent folder
import os
import sys
import inspect

currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0, parentdir) 

from hierarchy import Hierarchy

memory_instances = [
    MemoryInstance(
        name="rf_128B",
        size=128 * 8,
        r_bw=8,
        w_bw=8,
        r_cost=0.095,
        w_cost=0.095,
        area=0,
        r_port=1,
        w_port=1,
        rw_port=0,
        latency=1,
    ),

    MemoryInstance(
        name="rf_2B",
        size=16,
        r_bw=16,
        w_bw=16,
        r_cost=0.021,
        w_cost=0.021,
        area=0,
        r_port=2,
        w_port=2,
        rw_port=0,
        latency=1,
    ),


    MemoryInstance(
        name="sram_2MB",
        size=131072 * 16 * 8,
        r_bw=128 * 16,
        w_bw=128 * 16,
        r_cost=26.01 * 16,
        w_cost=23.65 * 16,
        area=0,
        r_port=1,
        w_port=1,
        rw_port=0,
        latency=1,
        min_r_granularity=64,
        min_w_granularity=64,
    ),

    MemoryInstance(
        name="dram",
        size=10000000000,
        r_bw=64,
        w_bw=64,
        r_cost=700,
        w_cost=750,
        area=0,
        r_port=0,
        w_port=0,
        rw_port=1,
        latency=1,
    )
]

def multiplier_array_dut():
    """Multiplier array variables"""
    multiplier_input_precision = [8, 8]
    multiplier_energy = 0.04
    multiplier_area = 1
    dimensions = {"D1": 32, "D2": 32}  # {'D1': ('K', 32), 'D2': ('C', 32)}

    multiplier = Multiplier(
        multiplier_input_precision, multiplier_energy, multiplier_area
    )
    multiplier_array = MultiplierArray(multiplier, dimensions)

    return multiplier_array

multiplier_array = multiplier_array_dut()

genome = np.array([
    # Instance 1
    0,      #Memory instance
    0,      #Operands
    1,
    0,
    0, 0,   #I1 ports
    0, 0,
    0, 0,
    0, 0,
    2, 1,   #I2 ports
    1, 1,
    0, 1,
    0, 1,
    0, 0,   #O ports
    0, 0,
    0, 0,
    0, 0,
    0, 0,   #Served dimensions
    
    #Instance 2
    1,      #Memory instance
    0,      #Operands
    0,
    1,
    0, 0,   #I1 ports
    0, 0,
    0, 0,
    0, 0,
    0, 0,   #I2 ports
    0, 0,
    0, 0,
    0, 0,
    2, 1,   #O ports
    1, 1,
    2, 2,
    1, 2,
    0, 1,   #Served dimensions
    
    #Instance 3
    2,      #Memory instance
    1,      #Operands
    0,
    1,
    2, 1,   #I1 ports
    1, 1,
    0, 1,
    0, 1,
    0, 0,   #I2 ports
    0, 0,
    0, 0,
    0, 0,
    2, 1,   #O ports
    1, 1,
    2, 1,
    1, 1,
    1, 1,   #Served dimensions
    
    #Instance 4
    3,      #Memory instance
    1,      #Operands
    1,
    1,
    3, 1,   #I1 ports
    3, 1,
    0, 1,
    0, 1,
    3, 1,   #I2 ports
    3, 1,
    0, 1,
    0, 1,
    3, 1,   #O ports
    3, 1,
    3, 1,
    3, 1,
    1, 1,   #Served dimensions
    ])


def main():
    h = Hierarchy(memory_instances, multiplier_array, genome)
    print('done')
    from zigzag.visualization.graph.memory_hierarchy import (
            visualize_memory_hierarchy_graph,
        )

    visualize_memory_hierarchy_graph(h.memory_hierarchy_graph)
    
    mapping = "/Users/rderi/Programming/Class/COSC461-S24/final/test/tpu_like.py"
    accelerator = h.get_accelerator()
    workload = "/Users/rderi/Programming/Class/COSC461-S24/final/test/alexnet.onnx"
    dump_filename_pattern=f"outputs/Edge_TPU-alexnet-layer_?.json"
    pickle_filename = f"outputs/Edge_TPU-alexnet-saved_list_of_cmes.pickle"
    energy, latency, cme = 0, 0, 0
    #try:
    energy, latency, cme = get_hardware_performance_zigzag(workload=workload,
                                                    accelerator=accelerator,
                                                    mapping=mapping,
                                                    opt='energy',
                                                    dump_filename_pattern=dump_filename_pattern,
                                                    pickle_filename=pickle_filename)
    #except Exception as e:
    #    print(e)    
    
    print(f"Total network energy = {energy:.2e} pJ")
    print(f"Total network latency = {latency:.2e} cycles")
    
if __name__ == "__main__":
    main()
```

**Comment by RobinGeens** [comment]
Hi rderi, as far as I can tell, this error is caused by a bug within Zigzag's SpatialMappingGenerator, and not by the way you use the API. Thank you for letting us know! 

I've just completely reworked the SpatialMappingGenerator and we're aiming to bring this into production within the next few weeks. If you would like to continue your work before then, I'd suggest you use the code from the `robin-dev` branch. However, there have been many other changes, and the docs have not been updated yet. If you're willing to give it a try, I can help in case you encounter new bugs.
